default_color_bg=
default_color_fg=white        # text (ctp text)
dialog_attr=
dialog_attr_selected=reverse
dialog_color_bg=
dialog_color_fg=white
dialog_shaded_color_bg=
dialog_shaded_color_fg=gray   # overlay0
entry_attr=
entry_color_bg=
entry_color_fg=white
help_attr=reverse
help_color_bg=
help_color_fg=white
history_name_attr=bold
history_name_attr_selected=reverse
history_name_recv_color_bg=
history_name_recv_color_fg=blue      # incoming = ctp blue
history_name_recv_group_color_bg=
history_name_recv_group_color_fg=mauve # group = ctp mauve
history_name_sent_color_bg=
history_name_sent_color_fg=green     # sent = ctp green
history_text_attachment_color_bg=
history_text_attachment_color_fg=flamingo
history_text_attr=
history_text_attr_selected=reverse
history_text_quoted_color_bg=
history_text_quoted_color_fg=yellow
history_text_reaction_color_bg=
history_text_reaction_color_fg=red
history_text_recv_color_bg=
history_text_recv_color_fg=blue
history_text_recv_group_color_bg=
history_text_recv_group_color_fg=mauve
history_text_sent_color_bg=
history_text_sent_color_fg=green
list_attr=
list_attr_selected=reverse
list_color_bg=
list_color_fg=white
list_color_unread_bg=
list_color_unread_fg=yellow    # unread highlight
listborder_attr=
listborder_color_bg=
listborder_color_fg=gray
status_attr=reverse
status_color_bg=
status_color_fg=white
top_attr=reverse
top_color_bg=
top_color_fg=white
